services:
  auth-service:
    build:
      context: app/auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  blog-service:
    build:
      context: app/blog-service
      dockerfile: Dockerfile
    ports:
      - "4000:8080"