services:
  auth-service:
    image: auth-service:latest
    env_file:
      - .env.authservice
    ports:
      - "3000:3000"

  blog-service:
    image: blog-service:latest
    env_file:
      - .env.blogservice
    ports:
      - "4000:8080"

  auth-db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3001:3306'
      expose:
        - '3001'
      volumes:
        - auth-db:/var/lib/mysql

  blog-db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: blogservicedb
        MYSQL_ROOT_PASSWORD: Test1234
        MYSQL_USER: blogdbuser
        MYSQL_PASSWORD: Test1234
      ports:
        - '4001:3306'
      expose:
        - '4001'
      volumes:
        - blog-db:/var/lib/mysql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '4002:4002'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
  auth-db:
    driver: local
  blog-db:
    driver: local
  cache:
    driver: local