name: 'Terraform Apply'

on:
  push:
    branches:
      - master

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: infra
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
      - name: Debug Files
        run: |
          ls -R
          
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Terraform Format'
        run: terraform fmt -check
        
      - name: 'Terraform Init'
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
      - name: 'Terraform Plan'
        run: terraform plan -var-file=vars.tfvars -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
      - name: 'Terraform Apply'
        run: |
          terraform apply -auto-approve tfplan