name: 'Terraform Apply'

on:
  push:
    branches:
      - master

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
      - name: Debug Files
        run: |
          ls -R
          
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Terraform Format'
        working-directory: .
        run: terraform fmt -check
        
      - name: 'Terraform Init'
        working-directory: .
        run: terraform init

      - name: 'Terraform Plan'
        working-directory: .
        run: terraform plan -var-file=vars.tfvars -out=tfplan

      - name: 'Terraform Apply'
        working-directory: .
        run: |
          terraform apply -auto-approve tfplan
