name: "Terraform"

on:
  push:
    branches:
      master
    paths:
      - .github/workflows/terraform.yml
      - infra/**

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=vars.tfvars

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file=vars.tfvars
